[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
key = "N"
mods = "Command"

[keyboard.bindings.command]
args = ["-n", "/Applications/Alacritty.app"]
program = "open"

[window]
decorations = "transparent"
dynamic_title = true

[window.padding]
x = 25
y = 40
